project: vehicle_train  # project name
model: yolov8n-seg.pt  # run name
#model: C:/traffic/yolov5-master/Traffic_Fix_clean_datasetv7/vehicle_train/train4/weights/last.pt  # path to model file, i.e. yolov8n-seg.pt, yolov8n.yaml
data: dataset.yaml  # path to dataset file, i.e. dataset.yaml
device: 0  # cuda device, i.e. 0 or 0,1,2,3 or cpu
epochs: 80  # number of epochs
batch: 8  # batch size
imgsz: 640  # image size
workers: 1  # number of workers threads for data loading
val: True  # run validation during training
plots: True  # save plots and images during train/val
resume: False  # resume training from checkpoint

augmentation: # https://docs.ultralytics.com/usage/cfg/#augmentation-settings
  hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
  hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
  hsv_v: 0.4  # image HSV-Value augmentation (fraction)
  degrees: 0.0  # image rotation (+/- deg)
  translate: 0.1  # image translation (+/- fraction)
  scale: 0.5  # image scale (+/- gain)
  shear: 0.0  # image shear (+/- deg)
  perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
  flipud: 0.0  # image flip up-down (probability)
  fliplr: 0.5  # image flip left-right (probability)
  bgr: 0.0  # image BGR permutation (probability)
  mosaic: 1.0  # image mosaic (probability)
  mixup: 0.0  # image mixup (probability)
  copy_paste: 0.0  # image copy-paste (probability)
  erasing: 0.4  # image random erasing (probability)
  crop_fraction: 1  # image random crop (fraction)


